# backend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy all files
COPY . .

# Run drizzle generate + migrate before dev server
CMD sh -c "npx drizzle-kit generate && npx drizzle-kit migrate && nodemon server.js"
