FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Install nodemon globally or as dev dependency
RUN npm install -g nodemon

COPY . .

EXPOSE 5000

CMD ["nodemon", "server.js"]
