# backend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Install nodemon globally (or skip if already in devDependencies)
RUN npm install -g nodemon

COPY . .

CMD ["nodemon", "server.js"]
